// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA52GWUNvxWvYGBDIrvZ4d4i3LXGGoyqAs',
    appId: '1:626709432503:web:3700bbba65f96d1100a532',
    messagingSenderId: '626709432503',
    projectId: 'run-anywhere-b962d',
    authDomain: 'run-anywhere-b962d.firebaseapp.com',
    storageBucket: 'run-anywhere-b962d.appspot.com',
    measurementId: 'G-B2J9RK4Q8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaxEIKCINs42GlJgnEyOSJOmnbna0erYY',
    appId: '1:626709432503:android:21a23f335042f72700a532',
    messagingSenderId: '626709432503',
    projectId: 'run-anywhere-b962d',
    storageBucket: 'run-anywhere-b962d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBdzRAKnKMNDEfX_rPlju7ggNbl2LQSE',
    appId: '1:626709432503:ios:aaf3b2e656a003cc00a532',
    messagingSenderId: '626709432503',
    projectId: 'run-anywhere-b962d',
    storageBucket: 'run-anywhere-b962d.appspot.com',
    iosBundleId: 'jp.hatahata.runAnywhere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBdzRAKnKMNDEfX_rPlju7ggNbl2LQSE',
    appId: '1:626709432503:ios:d07fddfaa3ace5c700a532',
    messagingSenderId: '626709432503',
    projectId: 'run-anywhere-b962d',
    storageBucket: 'run-anywhere-b962d.appspot.com',
    iosBundleId: 'com.example.runGpuAnywhere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA52GWUNvxWvYGBDIrvZ4d4i3LXGGoyqAs',
    appId: '1:626709432503:web:d12f8befdfa5ce2200a532',
    messagingSenderId: '626709432503',
    projectId: 'run-anywhere-b962d',
    authDomain: 'run-anywhere-b962d.firebaseapp.com',
    storageBucket: 'run-anywhere-b962d.appspot.com',
    measurementId: 'G-Z81N1HHDHN',
  );
}
