name: Build and Release Android App

on:
  push:
    branches:
      - main

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  deploy_android_app:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "install firebase CLI"
        run: |
          curl -sL https://firebase.tools | bash

      - name: "Read flutter version from fvm config"
        id: flutter_info
        run: |
          FLUTTER_VERSION=$(grep 'flutter' .tool-versions | awk '{print $2}' | sed 's/-.*//')
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name : "Install dependencies"
        run: |
          flutter packages pub get
          dart run build_runner build

      - name: Build Android app
        run: |
          flutter build apk
      
      - name: "Deploy to Firebase App Distribution"
        run: |
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            --groups "github"
